#!/usr/bin/env python
"""gpx-to-kafka

Usage: ./gpx-to-kafka filename.gpx

Will parse file and send to Kafka:
userhash,timestamp,latitude,longitude,accuracy

"""
import datetime as dt
import hashlib
import gpxpy
import gpxpy.gpx
import argparse
from kafka import KafkaClient, SimpleProducer

# Kafka
# Update this part to relevant locations
localhost = '9092'
topic = 'test'
accuracy = 0.15

def main():
    parser = argparse.ArgumentParser(description='Process some gpx file.')
    parser.add_argument('gpx_file', help='file to process.')
    args = parser.parse_args()
    gpx_file = open(args.gpx_file, 'r')
    user_timestamp_md5 = hashlib.md5(''.join(args.gpx_file.split('.')[:-1])).hexdigest()
    gpx = gpxpy.parse(gpx_file)

    kafka = KafkaClient("localhost:" + localhost)
    producer = SimpleProducer(kafka)
    for track in gpx.tracks:
        for segment in track.segments:
            for point in segment.points:
                timestamp = int(point.time.strftime('%s')) - int(dt.datetime(1970, 1, 1).strftime('%s'))
                print_message = [u  ser_timestamp_md5,
                                 str(timestamp),
                                 str(point.latitude),
                                 str(point.longitude),
                                 str(accuracy),
                                 ]
                producer.send_messages(topic, "/".join(print_message))

if __name__ == "__main__":
    main()
